#!/usr/bin/env bash
set -e

DOTFILES_DIR="/tmp/dotfiles"

if [[ ! -d "${NVIM_HOME}" ]]; then
    echo "Doing initial install of Neovim plugins... (this might take a while)"
    git clone https://github.com/nachovizzo/dotfiles.git ${DOTFILES_DIR}

    mkdir -p ${HOME}/.config/
    cp -R ${DOTFILES_DIR}/.config/nvim/ ${HOME}/.config/
    source ${DOTFILES_DIR}/.config/yadm/functions.sh
    install_neovim_extensions

    echo "Initial install of Neovim plugins done."
    rm -rf ${DOTFILES_DIR}/
else
    echo "Neovim plugins already initialized! Skiping..."
fi
