#!/usr/bin/env bash

if [[ ! -d "${NVIM_HOME}" ]]; then
    echo "Doing initial install of Neovim plugins:"
    git clone https://github.com/nachovizzo/dotfiles.git

    source dotfiles/.config/yadm/functions.sh
    install_neovim_extensions

    echo "Initial install of Neovim plugins done."
fi
