#!/usr/bin/env bash
# Inspired by ade-atom, modified by Ignacio Vizzo
# Copyright 2018 Apex.AI, Inc.
# SPDX-License-Identifier: Apache-2.0

set -xe

cd "$(dirname "$(realpath "$0")")"

NEOVIM_VERSION="$1"
NODE_VERSION="v18.17.1"
CLANGD_VERSION="16.0.2"

shift

# Download and install Neovim
curl -LO "https://github.com/neovim/neovim/releases/download/${NEOVIM_VERSION}/nvim-linux64.tar.gz"
tar xzf nvim-linux64.tar.gz
mv nvim-linux64 _opt_neovim
rm nvim-linux64.tar.gz

# Install NodeJS. Otherwise nvim is not really usefull
curl -LO https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz
tar -xf node-${NODE_VERSION}-linux-x64.tar.xz
cp -R node-${NODE_VERSION}-linux-x64/* _opt_neovim/
rm -rf node-${NODE_VERSION}-linux-x64/
rm node-${NODE_VERSION}-linux-x64.tar.xz

# Install clangd, otherwise nvim is not that great
curl -LO https://github.com/clangd/clangd/releases/download/${CLANGD_VERSION}/clangd-linux-${CLANGD_VERSION}.zip
unzip clangd-linux-${CLANGD_VERSION}.zip
cp -R clangd_${CLANGD_VERSION}/* _opt_neovim/
rm -rf clangd_${CLANGD_VERSION}/
rm clangd-linux-${CLANGD_VERSION}.zip

# Environment Setup
cp env.sh _opt_neovim/.env.sh
cp adeinit _opt_neovim/.adeinit

# Use _opt_neovim for readability, rename to _opt b/c it's expected by Dockerfile
mv _opt_neovim _opt
