name: Build and Push Docker Image

# TODO: add on-tag rule
on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
        # uses: docker/login-action@v1
        # with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build opt/
        run: ./build-opt v0.9.1
      - name: Build and Push Docker Image
        run: |
          docker build -t --label ade_image_commit_sha="$(COMMIT_SHA)" --label ade_image_commit_tag="$(COMMIT_TAG)"  nachovizzo/ade-nvim:latest .
          # docker push nachovizzo/ade-nvim:latest
